[package]
name = "brute-sha1-challenge-rust"
version = "0.1.0"
authors = ["Wendell Magallanes <waveform.999@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto = "^0.2"
arguments = "^0.6.2"